# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "Database"
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision :shell, :path => "setup.sh"
  config.vm.network "private_network", ip: "192.168.50.21", virtualbox__intnet: "cf"
  config.vm.network :forwarded_port, guest: 7474, host: 4242
  config.vm.synced_folder "../../data/", "/vagrant/data"
end
